# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main] # FIXME: please add the branch name on which you wanna publish the package
  pull_request:
    branches: ["*"] # FIXME: Please add your preferred branch to get a pull request {currently we are using all branches to make a pull request}

jobs:
  build:
    runs-on: ubuntu-latest # FIXME: You can add different os as well such as [windows-latest]

    strategy:
      matrix:
        node-version: [14.x]
        # os: [ubuntu-latest, windows-latest] # FIXME: pleas do add this line if you wish to use different os's

    # TODO: To create add just edit in here
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # FIXME: if you are using different platform please follow here: https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # TODO: Create NPM_TOKEN from npmjs and add it to your preferred CI in here i am using github-actions
        run: npx semantic-release
